[Autologin]
User=aidrax
Session=aidrax
Relogin=true

[General]
DisplayServer=x11
GreeterEnvironment=QT_QUICK_BACKEND=software
HaltCommand=/usr/bin/systemctl poweroff
RebootCommand=/usr/bin/systemctl reboot

[Theme]
Current=aidrax
